### PR TITLE
Update dependencies and fix broken Travis build

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@JakeWharton

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@JakeWharton Sorry for the unintentionally large PR, it took some effort to finally get the Travis build up and running again.

**Comment by SUPERCILEX** [comment]
@JakeWharton

**Comment by JakeWharton** [comment]
@SUPERCILEX

**Comment by SUPERCILEX** [comment]
Lol, can you take a look? 😄

**Comment by SUPERCILEX** [comment]
@JakeWharton Can you forward this along to whoever maintains this repo? Thanks!

**Comment by SUPERCILEX** [comment]
@JakeWharton Hello?

**Comment by SUPERCILEX** [comment]
@JakeWharton?

**Pull request closed without merging**
