### PR TITLE
Update to Kotlin version to 0.13.1513

### PR DESCRIPTION
**Pull request by steindekker**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Why the revert of the plugin and tools update?

**Comment by JakeWharton** [comment]
Can you squash these commits into one?

**Comment by steindekker** [comment]
Done.

I have used build tools 22 because Travis CI failed with build tools 23.

**Comment by JakeWharton** [comment]
Thanks! I'll look at the tools things separately then.

**Pull request merged**
