### PR TITLE
Really fix CI build, update dependencies, update Gradle

### PR DESCRIPTION
**Pull request by jaredsburrows**
@JakeWharton 

Folding https://github.com/JakeWharton/kotterknife/pull/65 into here

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@JakeWharton Please merge, otherwise JitPack.io is broken

**Comment by JakeWharton** [comment]
JitPack isn't a supported distribution mechanism of the project.

**Comment by jaredsburrows** [comment]
@JakeWharton It does work: https://jitpack.io/#JakeWharton/kotterknife/ad010a8387.

**Comment by SUPERCILEX** [comment]
@JakeWharton Since you don't provide a jcenter, JitPack is the only viable option right now (excluding copy pasting everything). As long as the build works, JitPack works. 😄

**Comment by jaredsburrows** [comment]
@SUPERCILEX All of @JakeWharton's libraries are offered via `mavenCentral()`.

**Comment by SUPERCILEX** [comment]
@jaredsburrows The README says
> Currently not available via Maven Central.

Instead, he's got a dev build thing going with Sonatype.

**Comment by jaredsburrows** [comment]
Yeah sorry. Both of my responses were too short.

All repos can be support via Jitpack. @JakeWharton was just saying that he is "only" supporting Maven Central. If it works with Jitpack then it works with Jitpack.

Since he mainly uses Maven Central, you have to wait for release. So in your case, Jitpack is the best solution as of now.

And yes, the readme, this has always been a snapshot, you are right.

**Pull request merged**
